import "./globals.css";
import { ToastContainer } from "react-toastify";

import "react-toastify/dist/ReactToastify.css";
import Provider from "@/Component/Provider";
import UserContextProvider from "@/context/UserContextProvider";
import ProtectedRouting from "@/Component/ProtectedRouting/ProtectedRouting";
import NavBar from "@/Component/Navbar/NavBar";
import { Container } from "@mui/material";
// import ProtectedRouting from "@/Component/ProtectedRouting/ProtectedRouting";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Container maxWidth="">
      <UserContextProvider >
        <Provider>
        <NavBar/>
        {/* <ProtectedRouting> */}
          {children}
          {/* </ProtectedRouting> */}
        </Provider>
        <ToastContainer />
        </UserContextProvider>
        
</Container>
      </body>
    </html>
  );
}
